import json
from pathlib import Path

from stable_asr.paper.experiments import run_paper_smoke
from stable_asr.paper.figures import PAPER_FIGURES, paper_figure


def test_paper_figures_generate_svg_files(tmp_path: Path) -> None:
    result = run_paper_smoke(tmp_path / "paper", episodes=8, seed=4, train_model=False)

    for figure in PAPER_FIGURES:
        output = tmp_path / f"{figure}.svg"
        generated = paper_figure(result.results_path, figure, output)
        svg = output.read_text(encoding="utf-8")

        assert generated == str(output)
        assert svg.startswith("<svg")
        assert "Generated by stable-asr paper-figure" in svg


def test_paper_architecture_figure_documents_platform_layers(tmp_path: Path) -> None:
    result = run_paper_smoke(tmp_path / "paper", episodes=8, seed=4, train_model=False)
    output = tmp_path / "architecture.svg"

    paper_figure(result.results_path, "architecture", output)
    svg = output.read_text(encoding="utf-8")

    assert "Stable-ASR Platform Architecture" in svg
    assert "Data Layer" in svg
    assert "Model and Adapter Layer" in svg
    assert "Policy and Scenario Layer" in svg
    assert "Evaluation and Paper Layer" in svg


def test_paper_target_figures_cover_data_robustness_and_pareto(tmp_path: Path) -> None:
    result = run_paper_smoke(tmp_path / "paper", episodes=8, seed=4, train_model=False)

    checks = {
        "data_registry": "Data Format Registry",
        "robustness_heatmap": "VoiceWorld Robustness Heatmap",
        "latency_quality_pareto": "Latency-Quality Pareto",
    }
    for figure, expected_title in checks.items():
        output = tmp_path / f"{figure}.svg"
        paper_figure(result.results_path, figure, output)
        svg = output.read_text(encoding="utf-8")

        assert expected_title in svg
        assert "Generated by stable-asr paper-figure" in svg


def test_data_figure_handles_skipped_optional_backend(tmp_path: Path) -> None:
    result = run_paper_smoke(tmp_path / "paper", episodes=8, seed=4, train_model=False)
    results_path = Path(result.results_path)
    payload = json.loads(results_path.read_text(encoding="utf-8"))
    payload["data"]["benchmark"] = {
        "status": "skipped",
        "reason": "Parquet support requires pyarrow",
        "rows": [],
    }
    results_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    output = tmp_path / "data.svg"

    paper_figure(results_path, "data", output)
    svg = output.read_text(encoding="utf-8")

    assert "Data Format Size Unavailable" in svg
    assert "Parquet support requires pyarrow" in svg
    assert "Generated by stable-asr paper-figure" in svg


def test_paper_figure_rejects_unknown_figure(tmp_path: Path) -> None:
    result = run_paper_smoke(tmp_path / "paper", episodes=8, seed=4, train_model=False)

    try:
        paper_figure(result.results_path, "unknown", tmp_path / "unknown.svg")
    except ValueError as exc:
        assert "unknown paper figure" in str(exc)
    else:
        raise AssertionError("paper_figure should reject unknown figures")
